フロントエンドでmp4からwavへの変換、保存
shinya09/OJT pull request #2
Opened 2020-11-30 02:29 UTC by shinya09

AB#168

2020-11-30 09:01 UTC, arakawa-jrits requested changes

2020-11-30 09:01 UTC, arakawa-jrits commented on src/index.tsx
> -  <React.StrictMode>
StrictMode を削ったのは何故でしょう？
基本的に削除する必要はなく、むしろ積極的に使うべき機能のように見えますが・・・
https://ja.reactjs.org/docs/strict-mode.html

2020-12-01 02:44 UTC, shinya09 commented on src/App.tsx
> +      ffmpeg.FS('writeFile',file.name,await fetchFile(file));
https://github.com/ffmpegwasm/ffmpeg.wasm/blob/master/docs/api.md#ffmpeg-fs
↑のページを見る限り一度保存する必要があると思います

2020-12-01 02:49 UTC, shinya09 commented on src/App.tsx
> +  private async videoConverter(file:File):Promise<File> {
extractAudioは不要と判断して削除しました

2020-12-02 00:25 UTC, arakawa-jrits commented on src/App.tsx
> +      ffmpeg.FS('writeFile',file.name,await fetchFile(file));
リンク先のリンク先を読んで理解しました。普通のファイルとして書いているのかと思っていましたが、memfs なら問題ないです。

2020-12-03 01:25 UTC, arakawa-jrits requested changes

2020-12-03 02:10 UTC, shinya09 commented on .gitignore
> +/my-app-typescript/node_modules
修正しました

2020-12-03 02:12 UTC, shinya09 commented on express-nodejs/index.ts
> +import express from 'express'
以後気をつけます。

2020-12-03 02:54 UTC, shinya09 commented on my-app-typescript/src/App.tsx
> +interface SquareStateInterface {
具体的にどんな名前にするとよいのでしょうか？

2020-12-07 08:16 UTC, arakawa-jrits approved these changes

2020-12-08 00:54 UTC, merged